# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.AutoField(db_column='addressID', primary_key=True, serialize=False)),
                ('addressline1', models.CharField(blank=True, db_column='addressLine1', max_length=100, null=True)),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('parameters', models.CharField(blank=True, max_length=1000, null=True)),
                ('responsecode', models.IntegerField(blank=True, db_column='responseCode', null=True)),
                ('ipaddress', models.CharField(blank=True, db_column='ipAddress', max_length=100, null=True)),
                ('requesttype', models.CharField(blank=True, db_column='requestType', max_length=100, null=True)),
                ('requesttime', models.IntegerField(blank=True, db_column='requestTime', null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.AutoField(db_column='feedbackID', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('statement', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('orderdetailsid', models.AutoField(db_column='orderDetailsID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('sellprice', models.IntegerField(blank=True, db_column='sellPrice', null=True)),
                ('buyprice', models.IntegerField(blank=True, db_column='buyPrice', null=True)),
            ],
            options={
                'db_table': 'OrderDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='orderID', primary_key=True, serialize=False)),
                ('orderdate', models.DateField(blank=True, db_column='orderDate', null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(db_column='productID', primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, db_column='productName', max_length=100, null=True)),
                ('productcode', models.CharField(blank=True, db_column='productCode', max_length=100, null=True)),
                ('quantityinstock', models.IntegerField(blank=True, db_column='quantityInStock', null=True)),
                ('buyprice', models.IntegerField(blank=True, db_column='buyPrice', null=True)),
                ('sellprice', models.IntegerField(blank=True, db_column='sellPrice', null=True)),
                ('productdescription', models.CharField(blank=True, db_column='productDescription', max_length=1000, null=True)),
                ('isavailable', models.IntegerField(blank=True, db_column='isAvailable', null=True)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('customername', models.CharField(blank=True, db_column='customerName', max_length=100, null=True)),
                ('contactfirstname', models.CharField(blank=True, db_column='contactFirstName', max_length=100, null=True)),
                ('contactlastname', models.CharField(blank=True, db_column='contactLastName', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
