# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_catego'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
