# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160716_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
