username = 'pverma'
password = 'pverma'
host = 'aline-cnu-insights-dev.czuocyoc6awe.us-east-1.rds.amazonaws.com'
database = 'cnu2016_pverma'
# region = 'us-east-1'
# queueName = 'cnu2016_pverma_assignment05'